Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

Data Loading

In [6]:
df=pd.read_csv("final_dataset.csv")
df.head()

                                                text     emotion
0  i feel rather funny ending with so many dupes ...         fun
1                     i feel surprised by the result    surprise
2                    i am officially feeling festive     neutral
3  i suddenly found myself standing before this w...    surprise
4  i look at the meager pile of food i purchased ...  enthusiasm

Drop missing data

In [7]:
df.isnull().sum()
df = df[['text', 'emotion']] 
df.dropna(inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106355 entries, 0 to 106354
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   text     106355 non-null  object
 1   emotion  106355 non-null  object
dtypes: object(2)
memory usage: 1.6+ MB

In [9]:
df.groupby('emotion')['emotion'].count()

emotion
anger         10000
empty          6358
enthusiasm    10000
fun           10000
happiness     10000
hate          10000
love          10000
neutral        9998
relief        10000
sadness        9999
surprise      10000
Name: emotion, dtype: int64

Text Processing

In [10]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+|#\w+", "", text)
    text = re.sub(r"[^a-z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [11]:
df['clean_text'] = df['text'].apply(clean_text)
df.head()

,text,emotion,clean_text
0,i feel rather funny ending with so many dupes ...,fun,i feel rather funny ending with so many dupes ...
1,i feel surprised by the result,surprise,i feel surprised by the result
2,i am officially feeling festive,neutral,i am officially feeling festive
3,i suddenly found myself standing before this w...,surprise,i suddenly found myself standing before this w...
4,i look at the meager pile of food i purchased ...,enthusiasm,i look at the meager pile of food i purchased ...

In [12]:
from sklearn.preprocessing import LabelEncoder

label_encoder=LabelEncoder()
df['emotion_encoded']=label_encoder.fit_transform(df['emotion'])

Train test split

In [13]:
x=df['clean_text']
y=df['emotion_encoded']

x_train, x_test, y_train, y_test = train_test_split(x,y,
    test_size=0.2,
    random_state=42
)

TF-IDF Feature Extraction

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(max_features=5000,ngram_range=(1,2))
x_train_tfidf=vectorizer.fit_transform(x_train)
x_test_tfidf=vectorizer.transform(x_test)

Support Vector Machine

In [15]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
svm_model=LinearSVC(class_weight='balanced')
svm_model.fit(x_train_tfidf,y_train)

LinearSVC(class_weight='balanced')

In [16]:
y_pred = svm_model.predict(x_test_tfidf)
svm_acc=accuracy_score(y_test,y_pred)
svm_acc

0.8308965257862818

Saved Model

In [17]:
import joblib
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')
joblib.dump(svm_model, 'svm_model.pkl')
joblib.dump(label_encoder, "label_encoder.pkl")

['label_encoder.pkl']